//*
// Detailed description can be found at Message structure
// document located at our Google Disk

//*
// This example module contains devices Blinker and Lights.
// For an example of the blinker behavior, there would be two distinct devices of type BLINKER, but one would be named
// RightBlinker and would get command TURN_ON when the blinker lever would be pushed up.
// The second one would be named LeftBlinker and would get the command TURN_ON when the lever would be pushed down.
// Both would get TURN_OFF in the lever's neutral position.
//
// The LIGHTS device has only a button, which switches them on and off.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: modules/ExampleModule.proto

package ba_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlinkerCommand_Command int32

const (
	BlinkerCommand_TURN_ON  BlinkerCommand_Command = 0
	BlinkerCommand_TURN_OFF BlinkerCommand_Command = 1
)

// Enum value maps for BlinkerCommand_Command.
var (
	BlinkerCommand_Command_name = map[int32]string{
		0: "TURN_ON",
		1: "TURN_OFF",
	}
	BlinkerCommand_Command_value = map[string]int32{
		"TURN_ON":  0,
		"TURN_OFF": 1,
	}
)

func (x BlinkerCommand_Command) Enum() *BlinkerCommand_Command {
	p := new(BlinkerCommand_Command)
	*p = x
	return p
}

func (x BlinkerCommand_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlinkerCommand_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_ExampleModule_proto_enumTypes[0].Descriptor()
}

func (BlinkerCommand_Command) Type() protoreflect.EnumType {
	return &file_modules_ExampleModule_proto_enumTypes[0]
}

func (x BlinkerCommand_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlinkerCommand_Command.Descriptor instead.
func (BlinkerCommand_Command) EnumDescriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{2, 0}
}

type LightsCommand_Command int32

const (
	LightsCommand_PRESS LightsCommand_Command = 0
)

// Enum value maps for LightsCommand_Command.
var (
	LightsCommand_Command_name = map[int32]string{
		0: "PRESS",
	}
	LightsCommand_Command_value = map[string]int32{
		"PRESS": 0,
	}
)

func (x LightsCommand_Command) Enum() *LightsCommand_Command {
	p := new(LightsCommand_Command)
	*p = x
	return p
}

func (x LightsCommand_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LightsCommand_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_ExampleModule_proto_enumTypes[1].Descriptor()
}

func (LightsCommand_Command) Type() protoreflect.EnumType {
	return &file_modules_ExampleModule_proto_enumTypes[1]
}

func (x LightsCommand_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LightsCommand_Command.Descriptor instead.
func (LightsCommand_Command) EnumDescriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{3, 0}
}

type BlinkerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFlashing bool `protobuf:"varint,1,opt,name=isFlashing,proto3" json:"isFlashing,omitempty"`
}

func (x *BlinkerStatus) Reset() {
	*x = BlinkerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlinkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkerStatus) ProtoMessage() {}

func (x *BlinkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkerStatus.ProtoReflect.Descriptor instead.
func (*BlinkerStatus) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{0}
}

func (x *BlinkerStatus) GetIsFlashing() bool {
	if x != nil {
		return x.IsFlashing
	}
	return false
}

type LightsStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOn bool `protobuf:"varint,1,opt,name=isOn,proto3" json:"isOn,omitempty"`
}

func (x *LightsStatus) Reset() {
	*x = LightsStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightsStatus) ProtoMessage() {}

func (x *LightsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightsStatus.ProtoReflect.Descriptor instead.
func (*LightsStatus) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{1}
}

func (x *LightsStatus) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

type BlinkerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command BlinkerCommand_Command `protobuf:"varint,1,opt,name=command,proto3,enum=ExampleModule.BlinkerCommand_Command" json:"command,omitempty"`
}

func (x *BlinkerCommand) Reset() {
	*x = BlinkerCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlinkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkerCommand) ProtoMessage() {}

func (x *BlinkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkerCommand.ProtoReflect.Descriptor instead.
func (*BlinkerCommand) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{2}
}

func (x *BlinkerCommand) GetCommand() BlinkerCommand_Command {
	if x != nil {
		return x.Command
	}
	return BlinkerCommand_TURN_ON
}

type LightsCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command LightsCommand_Command `protobuf:"varint,1,opt,name=command,proto3,enum=ExampleModule.LightsCommand_Command" json:"command,omitempty"`
}

func (x *LightsCommand) Reset() {
	*x = LightsCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightsCommand) ProtoMessage() {}

func (x *LightsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightsCommand.ProtoReflect.Descriptor instead.
func (*LightsCommand) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{3}
}

func (x *LightsCommand) GetCommand() LightsCommand_Command {
	if x != nil {
		return x.Command
	}
	return LightsCommand_PRESS
}

type BlinkerError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *BlinkerError) Reset() {
	*x = BlinkerError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlinkerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkerError) ProtoMessage() {}

func (x *BlinkerError) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkerError.ProtoReflect.Descriptor instead.
func (*BlinkerError) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{4}
}

func (x *BlinkerError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LightsError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *LightsError) Reset() {
	*x = LightsError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_ExampleModule_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightsError) ProtoMessage() {}

func (x *LightsError) ProtoReflect() protoreflect.Message {
	mi := &file_modules_ExampleModule_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightsError.ProtoReflect.Descriptor instead.
func (*LightsError) Descriptor() ([]byte, []int) {
	return file_modules_ExampleModule_proto_rawDescGZIP(), []int{5}
}

func (x *LightsError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_modules_ExampleModule_proto protoreflect.FileDescriptor

var file_modules_ExampleModule_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x2f, 0x0a, 0x0d,
	0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x22, 0x0a,
	0x0c, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x73, 0x4f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f,
	0x6e, 0x22, 0x77, 0x0a, 0x0e, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x55, 0x52, 0x4e, 0x5f, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x55, 0x52, 0x4e, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x22, 0x65, 0x0a, 0x0d, 0x4c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x14, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x3e, 0x5a, 0x21, 0x2e, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x61, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x18,
	0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x62, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_ExampleModule_proto_rawDescOnce sync.Once
	file_modules_ExampleModule_proto_rawDescData = file_modules_ExampleModule_proto_rawDesc
)

func file_modules_ExampleModule_proto_rawDescGZIP() []byte {
	file_modules_ExampleModule_proto_rawDescOnce.Do(func() {
		file_modules_ExampleModule_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_ExampleModule_proto_rawDescData)
	})
	return file_modules_ExampleModule_proto_rawDescData
}

var file_modules_ExampleModule_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_modules_ExampleModule_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_modules_ExampleModule_proto_goTypes = []interface{}{
	(BlinkerCommand_Command)(0), // 0: ExampleModule.BlinkerCommand.Command
	(LightsCommand_Command)(0),  // 1: ExampleModule.LightsCommand.Command
	(*BlinkerStatus)(nil),       // 2: ExampleModule.BlinkerStatus
	(*LightsStatus)(nil),        // 3: ExampleModule.LightsStatus
	(*BlinkerCommand)(nil),      // 4: ExampleModule.BlinkerCommand
	(*LightsCommand)(nil),       // 5: ExampleModule.LightsCommand
	(*BlinkerError)(nil),        // 6: ExampleModule.BlinkerError
	(*LightsError)(nil),         // 7: ExampleModule.LightsError
}
var file_modules_ExampleModule_proto_depIdxs = []int32{
	0, // 0: ExampleModule.BlinkerCommand.command:type_name -> ExampleModule.BlinkerCommand.Command
	1, // 1: ExampleModule.LightsCommand.command:type_name -> ExampleModule.LightsCommand.Command
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_ExampleModule_proto_init() }
func file_modules_ExampleModule_proto_init() {
	if File_modules_ExampleModule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_ExampleModule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlinkerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_ExampleModule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightsStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_ExampleModule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlinkerCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_ExampleModule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightsCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_ExampleModule_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlinkerError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_ExampleModule_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightsError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_ExampleModule_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_ExampleModule_proto_goTypes,
		DependencyIndexes: file_modules_ExampleModule_proto_depIdxs,
		EnumInfos:         file_modules_ExampleModule_proto_enumTypes,
		MessageInfos:      file_modules_ExampleModule_proto_msgTypes,
	}.Build()
	File_modules_ExampleModule_proto = out.File
	file_modules_ExampleModule_proto_rawDesc = nil
	file_modules_ExampleModule_proto_goTypes = nil
	file_modules_ExampleModule_proto_depIdxs = nil
}
