#pragma once

#include <general_error_codes.h>
/**
 * @brief Specific error codes for internal_client
 */
enum ic_error_codes {
	CONTEXT_INCORRECT = RESERVED-1,
	TIMEOUT_OCCURRED = RESERVED-2,
	NO_COMMAND_AVAILABLE = RESERVED-3,
	UNABLE_TO_CONNECT = RESERVED-4,
	DEVICE_ALREADY_CONNECTED = RESERVED-5,
	MODULE_NOT_SUPPORTED = RESERVED-6,
	DEVICE_TYPE_NOT_SUPPORTED = RESERVED-7,
	HIGHER_PRIORITY_ALREADY_CONNECTED = RESERVED-8,
	COMMAND_INCORRECT = RESERVED-9,
	DEVICE_INCORRECT = RESERVED-10
};